Repository StackStorm/st2-docker, pull requests merged in 2019-05, with the labels that each got.

#174 Update docs on how to configure st2chatops
  README.md
  images/stackstorm-all/README.md
Labels: RFR

#175 Deprecate 'kubernetes-1ppc' in favor of stackstorm-ha
  README.md
  runtime/kubernetes-1ppc/README.md
  runtime/kubernetes-1ppc/configmaps.yml
  runtime/kubernetes-1ppc/externals/mongo.yml
  runtime/kubernetes-1ppc/externals/postgres.yml
  runtime/kubernetes-1ppc/externals/rabbitmq.yml
  runtime/kubernetes-1ppc/externals/redis.yml
  runtime/kubernetes-1ppc/init-st2.yml
  runtime/kubernetes-1ppc/st2.yml
Labels: RFR, documentation

#176 Remove stackstorm-all
  images/stackstorm-all/Dockerfile
  images/stackstorm-all/README.md
  images/stackstorm-all/mongod.init
  images/stackstorm-all/start_st2_services.sh
Labels: RFR, bug
